### ISSUE TITLE
验证码无法加载

### ISSUE THREAD

**Issue by Aries-liancf** [Perye/dokit#9]
演示平台不能登入，原因是验证码无法加载

**Comment by OneKe** [comment]
because redis is down，you can clone it then start it by yourself

**Comment by JakeWoki** [comment]
redis启动验证码也加载不出来，报错：
com.perye.dokit.exception.BadRequestException: Captcha 不存在: id is 1
	at com.perye.dokit.utils.ValidationUtil.isNull(ValidationUtil.java:19)
	at com.perye.dokit.service.impl.CaptchaServiceImpl.findById(CaptchaServiceImpl.java:61)
